artifact:
  details:
    - groupId: junit
      artifactId: junit
      version: 4.13.2

    - groupId: org.slf4j
      artifactId: slf4j-api
      version: 2.0.16

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib
      version: 2.0.20

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib-common
      version: 2.0.20

    - groupId: com.google.guava
      artifactId: guava
      version: 33.3.0-jre

    - groupId: org.scala-lang
      artifactId: scala-library
      version: 2.13.14

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib-jdk8
      version: 2.0.20

    - groupId: org.mockito
      artifactId: mockito-core
      version: 5.12.0

    - groupId: com.fasterxml.jackson.core
      artifactId: jackson-databind
      version: 2.17.2

    - groupId: org.apache.commons
      artifactId: commons-lang3
      version: 3.16.0

    - groupId: commons-io
      artifactId: commons-io
      version: 2.16.1

    - groupId: ch.qos.logback
      artifactId: logback-classic
      version: 1.5.7

    - groupId: org.projectlombok
      artifactId: lombok
      version: 1.18.34

    - groupId: com.google.code.gson
      artifactId: gson
      version: 2.11.0

    - groupId: com.android.support
      artifactId: appcompat-v7
      version: 28.0.0
      repository:
        id: google
        url: https://maven.google.com/

    - groupId: javax.servlet
      artifactId: javax.servlet-api
      version: 4.0.1

    - groupId: org.clojure
      artifactId: clojure
      version: 1.11.4

    - groupId: log4j
      artifactId: log4j
      version: 1.2.17

    - groupId: org.scalatest
      artifactId: scalatest_3
      version: 3.2.19

    - groupId: org.assertj
      artifactId: assertj-core
      version: 3.26.3

    - groupId: org.slf4j
      artifactId: slf4j-reload4j
      version: 2.0.16

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter-api
      version: 5.11.0

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter-engine
      version: 5.11.0

    - groupId: org.slf4j
      artifactId: slf4j-simple
      version: 2.0.16

    - groupId: com.fasterxml.jackson.core
      artifactId: jackson-core
      version: 2.17.2

    - groupId: org.mockito
      artifactId: mockito-all
      version: 1.10.19

    - groupId: org.apache.httpcomponents
      artifactId: httpclient
      version: 4.5.14

    - groupId: com.google.code.findbugs
      artifactId: jsr305
      version: 3.0.2

    - groupId: org.springframework
      artifactId: spring-context
      version: 6.1.12

    - groupId: com.fasterxml.jackson.core
      artifactId: jackson-annotations
      version: 2.17.2

    - groupId: androidx.appcompat
      artifactId: appcompat
      version: 1.7.0
      repository:
        id: google
        url: https://maven.google.com/

    - groupId: org.renjin
      artifactId: stats
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: utils
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: grDevices
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: methods
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: graphics
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId:  datasets
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: tools
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: stats4
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: parallel
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: splines
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: grid
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: tcltk
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: compiler
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: commons-codec
      artifactId: commons-codec
      version: 1.17.1

    - groupId: commons-lang
      artifactId: commons-lang
      version: 2.6

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-test
      version: 3.3.3

    - groupId: javax.servlet
      artifactId: servlet-api
      version: 2.5

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-web
      version: 3.3.3

    - groupId: commons-logging
      artifactId: commons-logging
      version: 1.3.4

    - groupId: org.testng
      artifactId: testng
      version: 7.10.2

    - groupId: org.apache.logging.log4j
      artifactId: log4j-core
      version: 2.23.1

    - groupId: com.squareup.okhttp3
      artifactId:  okhttp
      version: 4.12.0

    - groupId: org.springframework.boot
      artifactId: spring-boot-configuration-processor
      version: 3.3.3

    - groupId: org.springframework
      artifactId: spring-test
      version: 6.1.12

    - groupId: joda-time
      artifactId: joda-time
      version: 2.12.7

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter
      version: 5.11.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-reflect
      version: 2.0.20

    - groupId: org.apache.logging.log4j
      artifactId: log4j-api
      version: 2.23.1

    - groupId: org.slf4j
      artifactId: jcl-over-slf4j
      version: 2.0.16

    - groupId: org.springframework
      artifactId: spring-web
      version: 6.1.12

    - groupId: org.springframework.boot
      artifactId: spring-boot-autoconfigure
      version: 3.3.3

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter
      version: 3.3.3

    - groupId: org.springframework
      artifactId: spring-core
      version: 6.1.12

    - groupId: com.h2database
      artifactId:  h2
      version: 2.3.232

    - groupId: org.scala-lang
      artifactId: scala3-library_3
      version: 3.5.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib-jdk7
      version: 2.0.20

    - groupId: org.apache.maven
      artifactId: maven-plugin-api
      version: 3.9.9

    - groupId: org.hamcrest
      artifactId: hamcrest
      version: 3.0

    - groupId: org.apache.logging.log4j
      artifactId: log4j-slf4j-impl
      version: 2.23.1

    - groupId: com.mysql
      artifactId: mysql-connector-j
      version: 8.0.33

    - groupId: androidx.core
      artifactId: core-ktx
      version: 1.13.1
      repository:
        id: google
        url: https://maven.google.com/

    - groupId: org.jetbrains.kotlinx
      artifactId: kotlinx-coroutines-core
      version: 1.8.1

    - groupId: org.springframework
      artifactId: spring-beans
      version: 6.1.12

    - groupId: org.jetbrains
      artifactId: annotations
      version: 24.1.0

    - groupId: org.osgi
      artifactId: org.osgi.core
      version: 6.0.0

    - groupId: javax.inject
      artifactId: javax.inject
      version: 1

    - groupId: commons-collections
      artifactId: commons-collections
      version: 3.2.2

    - groupId: com.alibaba
      artifactId: fastjson
      version: 2.0.52

    - groupId: javax.annotation
      artifactId: javax.annotation-api
      version: 1.3.2

#    moved to artifact hamcrest
#    - groupId: org.hamcrest
#      artifactId: hamcrest-library
#      version: 3.0

    - groupId: javax.validation
      artifactId: validation-api
      version: 2.0.1.Final

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter-params
      version: 5.11.0

    - groupId: com.fasterxml.jackson.datatype
      artifactId: jackson-datatype-jsr310
      version: 2.17.2

    - groupId: org.clojure
      artifactId: tools.nrepl
      version: 0.2.13

    - groupId: javax.xml.bind
      artifactId: jaxb-api
      version: 2.3.1

    - groupId: org.jetbrains.kotlinx
      artifactId: kotlinx-coroutines-core-jvm
      version: 1.8.1

    - groupId: com.google.android.material
      artifactId: material
      version: 1.12.0
      repository:
        id: google
        url: https://maven.google.com/

    - groupId: ch.qos.logback
      artifactId: logback-core
      version: 1.5.7

    - groupId: org.json
      artifactId: json
      version: 20240303

    - groupId: clojure-complete
      artifactId: clojure-complete
      version: 0.2.5
      repository:
        id: clojars
        url: https://repo.clojars.org/


    - groupId: org.scala-js
      artifactId: scalajs-library_2.13
      version: 1.16.0

    - groupId: org.springframework
      artifactId: spring-webmvc
      version: 6.1.12

    - groupId: commons-beanutils
      artifactId: commons-beanutils
      version: 1.9.4

    - groupId: com.google.protobuf
      artifactId: protobuf-java
      version: 4.28.0

    - groupId: com.squareup.retrofit2
      artifactId: retrofit
      version: 2.11.0

    - groupId: org.apache.maven.plugin-tools
      artifactId: maven-plugin-annotations
      version: 3.15.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-android-extensions-runtime
      version: 2.0.20

#    moved to artifact hamcrest
#    - groupId: org.hamcrest
#      artifactId: hamcrest-core
#      version: 3.0

    - groupId: com.google.inject
      artifactId: guice
      version: 7.0.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib-js
      version: 2.1.0

    - groupId: org.apache.httpcomponents.core5
      artifactId: httpcore5
      version: 5.3.1

    - groupId: org.easymock
      artifactId: easymock
      version: 5.5.0

    - groupId: org.postgresql
      artifactId: postgresql
      version: 42.7.4

    - groupId: org.yaml
      artifactId: snakeyaml
      version: 2.3

    - groupId: org.apache.commons
      artifactId: commons-collections4
      version: 4.4

    - groupId: commons-cli
      artifactId: commons-cli
      version: 1.9.0

    - groupId: org.apache.maven
      artifactId: maven-core
      version: 3.9.9

    - groupId: jakarta.servlet
      artifactId: jakarta.servlet-api
      version: 6.1.0

    - groupId: org.apache.groovy
      artifactId: groovy-all
      version: 4.0.24

    - groupId: org.scalacheck
      artifactId: scalacheck
      version: 1.18.1

    - groupId: androidx.recyclerview
      artifactId: recyclerview
      version: 1.3.2

    - groupId: org.powermock
      artifactId: powermock-module-junit4
      version: 2.0.9

    - groupId: androidx.legacy
      artifactId: legacy-support-v4
      version: 1.0.0

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-actuator
      version: 3.4.0

    - groupId: org.springframework
      artifactId: spring-jdbc
      version: 6.2.0

    - groupId: org.hibernate.orm
      artifactId: hibernate-core
      version: 6.6.3.Final

    - groupId: org.mockito
      artifactId: mockito-junit-jupiter
      version: 5.14.2

    - groupId: androidx.annotation
      artifactId: annotation
      version: 1.9.1

    - groupId: org.junit.vintage
      artifactId: junit-vintage-engine
      version: 5.11.3

    - groupId: com.sun.xml.bind
      artifactId: jaxb-impl
      version: 4.0.5

    - groupId: org.reflections
      artifactId: reflections
      version: 0.10.2

    - groupId: com.fasterxml.jackson.dataformat
      artifactId: jackson-dataformat-yaml
      version: 2.18.2

    - groupId: com.squareup.okhttp3
      artifactId: logging-interceptor
      version: 4.12.0

    - groupId: org.scala-lang
      artifactId: scala-reflect
      version: 2.13.15

    - groupId: org.hibernate.validator
      artifactId: hibernate-validator
      version: 8.0.1.Final

    - groupId: org.apache.commons
      artifactId: commons-compress
      version: 1.27.1

    - groupId: org.slf4j
      artifactId: jul-to-slf4j
      version: 2.0.16

    - groupId: org.springframework
      artifactId: spring-tx
      version: 6.2.0

    - groupId: org.slf4j
      artifactId: log4j-over-slf4j
      version: 2.0.16

    - groupId: org.eclipse.jetty
      artifactId: jetty-server
      version: 12.0.15

    - groupId: org.bouncycastle
      artifactId: bcprov-jdk18on
      version: 1.79

    - groupId: org.jsoup
      artifactId: jsoup
      version: 1.18.3

    - groupId: com.fasterxml.jackson.core
      artifactId: jackson-databind
      version: 2.18.2

    - groupId: com.squareup.retrofit2
      artifactId: converter-gson
      version: 2.11.0

    - groupId: org.springframework.boot
      artifactId: spring-boot
      version: 3.4.0

    - groupId: org.springframework
      artifactId: spring-context-support
      version: 6.2.0

    - groupId: org.osgi
      artifactId: osgi.cmpn
      version: 7.0.0

    - groupId: org.javassist
      artifactId: javassist
      version: 3.30.2-GA

    - groupId: org.apache.commons
      artifactId: commons-text
      version: 1.12.0

    - groupId: io.reactivex.rxjava3
      artifactId: rxjava
      version: 3.1.10

    - groupId: org.jetbrains.kotlinx
      artifactId: kotlinx-coroutines-android
      version: 1.9.0

    - groupId: jakarta.ws.rs
      artifactId: jakarta.ws.rs-api
      version: 4.0.0

    - groupId: jakarta.annotation
      artifactId: jakarta.annotation-api
      version: 3.0.0

    - groupId: org.codehaus.plexus
      artifactId: plexus-utils
      version: 4.0.2

    - groupId: org.aspectj
      artifactId: aspectjweaver
      version: 1.9.22.1

    - groupId: org.scala-js
      artifactId: scalajs-test-bridge
      version: 1.17.0

    - groupId: org.awaitility
      artifactId: awaitility
      version: 4.2.2

    - groupId: org.hsqldb
      artifactId: hsqldb
      version: 2.7.4

    - groupId: org.springframework
      artifactId: spring-aop
      version: 6.2.0

    - groupId: androidx.constraintlayout
      artifactId: constraintlayout
      version: 2.2.0

    - groupId: jakarta.xml.bind
      artifactId: jakarta.xml.bind-api
      version: 4.0.2

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-aop
      version: 3.4.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-dom-api-compat
      version: 2.1.0

    - groupId: com.github.bumptech.glide
      artifactId: glide
      version: 4.16.0

    - groupId: org.ow2.asm
      artifactId: asm
      version: 9.7.1

    - groupId: org.jetbrains.kotlinx
      artifactId: kotlinx-serialization-json-jvm
      version: 1.7.3

    - groupId: org.aspectj
      artifactId: aspectjrt
      version: 1.9.22.1

    - groupId: org.apache.hadoop
      artifactId: hadoop-common
      version: 3.4.1

    - groupId: androidx.recyclerview
      artifactId: recyclerview
      version: 1.3.2

    - groupId: xerces
      artifactId: xercesImpl
      version: 2.12.2

    - groupId: io.netty
      artifactId: netty-all
      version: 4.1.115.Final

    - groupId: org.powermock
      artifactId: powermock-api-mockito2
      version: 2.0.9

    - groupId:  org.apache.commons
      artifactId: commons-fileupload2-javax
      version: 2.0.0-M2

    - groupId: org.apache.httpcomponents.client5
      artifactId: httpclient5
      version: 5.4.1

    - groupId: javax.mail
      artifactId: javax.mail-api
      version: 1.6.2

    - groupId: com.github.ben-manes.caffeine
      artifactId: caffeine
      version: 3.1.8

    - groupId: org.renjin.cran
      artifactId: testthat
      version: 1.0.2-renjin-17

    - groupId: org.clojure
      artifactId: clojurescript
      version: 1.11.132

    - groupId: org.spockframework
      artifactId: spock-core
      version: 2.4-M4-groovy-4.0

    - groupId: org.freemarker
      artifactId: freemarker
      version: 2.3.33

    - groupId: com.zaxxer
      artifactId: HikariCP
      version: 6.2.1

    - groupId: com.typesafe
      artifactId: config
      version: 1.4.3

    - groupId: org.scala-js
      artifactId: scalajs-test-bridge
      version: 1.17.0

    - groupId: com.google.auto.service
      artifactId: auto-service
      version: 1.1.1

    - groupId: org.springframework
      artifactId: spring-orm
      version: 6.2.0

    - groupId: org.apache.poi
      artifactId: poi-ooxml
      version: 5.3.0

    - groupId: org.apache.commons
      artifactId: commons-math3
      version: 3.6.1

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-data-jpa
      version: 3.4.0

    - groupId: com.fasterxml.jackson.datatype
      artifactId: jackson-datatype-jdk8
      version: 2.18.2

    - groupId: io.rest-assured
      artifactId: rest-assured
      version: 5.5.0

    - groupId: dom4j
      artifactId: dom4j
      version: 1.6.1

    - groupId: javax.enterprise
      artifactId: cdi-api
      version: 2.0

    - groupId: org.slf4j
      artifactId: slf4j-jdk14
      version: 2.0.16

    - groupId: org.codehaus.groovy
      artifactId: groovy
      version: 3.0.23

    - groupId: com.fasterxml.jackson.module
      artifactId: jackson-module-kotlin
      version: 2.18.2

    - groupId: org.typelevel
      artifactId: cats-core
      version: 2.12.0

    - groupId: org.glassfish.jaxb
      artifactId: jaxb-runtime
      version: 4.0.5

    - groupId: org.apache.maven
      artifactId: maven-artifact
      version: 3.9.9

    - groupId: org.codehaus.jackson
      artifactId: jackson-core-asl
      version: 1.9.13

    - groupId: org.eclipse.jetty
      artifactId: jetty-servlet
      version: 11.0.24

    - groupId: org.junit.platform
      artifactId: junit-platform-launcher
      version: 1.11.3

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-test
      version: 2.1.0

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-validation
      version: 3.4.0