artifact:
  details:
    - groupId: junit
      artifactId: junit
      version: 4.13.2

    - groupId: org.slf4j
      artifactId: slf4j-api
      version: 2.0.16

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib
      version: 2.0.20

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib-common
      version: 2.0.20

    - groupId: com.google.guava
      artifactId: guava
      version: 33.3.0-jre

    - groupId: org.scala-lang
      artifactId: scala-library
      version: 2.13.14

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib-jdk8
      version: 2.0.20

    - groupId: org.mockito
      artifactId: mockito-core
      version: 5.12.0

    - groupId: com.fasterxml.jackson.core
      artifactId: jackson-databind
      version: 2.17.2

    - groupId: org.apache.commons
      artifactId: commons-lang3
      version: 3.16.0

    - groupId: commons-io
      artifactId: commons-io
      version: 2.16.1

    - groupId: ch.qos.logback
      artifactId: logback-classic
      version: 1.5.7

    - groupId: org.projectlombok
      artifactId: lombok
      version: 1.18.34

    - groupId: com.google.code.gson
      artifactId: gson
      version: 2.11.0

    # jar not available in maven
    #- groupId: com.android.support
    #  artifactId: appcompat-v7
    #  version: 28.0.0
    #  repository:
    #    id: google
    #    url: https://maven.google.com/

    - groupId: javax.servlet
      artifactId: javax.servlet-api
      version: 4.0.1

    - groupId: org.clojure
      artifactId: clojure
      version: 1.11.4

    - groupId: log4j
      artifactId: log4j
      version: 1.2.17

    - groupId: org.scalatest
      artifactId: scalatest_3
      version: 3.2.19

    - groupId: org.assertj
      artifactId: assertj-core
      version: 3.26.3

    - groupId: org.slf4j
      artifactId: slf4j-reload4j
      version: 2.0.16

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter-api
      version: 5.11.0

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter-engine
      version: 5.11.0

    - groupId: org.slf4j
      artifactId: slf4j-simple
      version: 2.0.16

    - groupId: com.fasterxml.jackson.core
      artifactId: jackson-core
      version: 2.17.2

    - groupId: org.mockito
      artifactId: mockito-all
      version: 1.10.19

    - groupId: org.apache.httpcomponents
      artifactId: httpclient
      version: 4.5.14

    - groupId: com.google.code.findbugs
      artifactId: jsr305
      version: 3.0.2

    - groupId: org.springframework
      artifactId: spring-context
      version: 6.1.12

    - groupId: com.fasterxml.jackson.core
      artifactId: jackson-annotations
      version: 2.17.2

# Jar not available
#    - groupId: androidx.appcompat
#      artifactId: appcompat
#      version: 1.7.0
    #  repository:
    #    id: google
    #    url: https://maven.google.com/

    - groupId: org.renjin
      artifactId: stats
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: utils
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: grDevices
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: methods
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: graphics
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId:  datasets
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: tools
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: stats4
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: parallel
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: splines
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: grid
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: tcltk
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: org.renjin
      artifactId: compiler
      version: 0.9.2723
      repository:
        id: bedatadriven
        url: https://nexus.bedatadriven.com/content/groups/public/

    - groupId: commons-codec
      artifactId: commons-codec
      version: 1.17.1

    - groupId: commons-lang
      artifactId: commons-lang
      version: 2.6

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-test
      version: 3.3.3

    - groupId: javax.servlet
      artifactId: servlet-api
      version: 2.5

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter-web
      version: 3.3.3

    - groupId: commons-logging
      artifactId: commons-logging
      version: 1.3.4

    - groupId: org.testng
      artifactId: testng
      version: 7.10.2

    - groupId: org.apache.logging.log4j
      artifactId: log4j-core
      version: 2.23.1

# Error: sootup can't process. Project is based on kotlin
#    - groupId: com.squareup.okhttp3
#      artifactId:  okhttp
#      version: 4.12.0

    - groupId: org.springframework.boot
      artifactId: spring-boot-configuration-processor
      version: 3.3.3

    - groupId: org.springframework
      artifactId: spring-test
      version: 6.1.12

    - groupId: joda-time
      artifactId: joda-time
      version: 2.12.7

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter
      version: 5.11.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-reflect
      version: 2.0.20

    - groupId: org.apache.logging.log4j
      artifactId: log4j-api
      version: 2.23.1

    - groupId: org.slf4j
      artifactId: jcl-over-slf4j
      version: 2.0.16

    - groupId: org.springframework
      artifactId: spring-web
      version: 6.1.12

    - groupId: org.springframework.boot
      artifactId: spring-boot-autoconfigure
      version: 3.3.3

    - groupId: org.springframework.boot
      artifactId: spring-boot-starter
      version: 3.3.3

    - groupId: org.springframework
      artifactId: spring-core
      version: 6.1.12

    - groupId: com.h2database
      artifactId:  h2
      version: 2.3.232

    - groupId: org.scala-lang
      artifactId: scala3-library_3
      version: 3.5.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-stdlib-jdk7
      version: 2.0.20

    - groupId: org.apache.maven
      artifactId: maven-plugin-api
      version: 3.9.9

    - groupId: org.hamcrest
      artifactId: hamcrest-all
      version: 1.3

    - groupId: org.apache.logging.log4j
      artifactId: log4j-slf4j-impl
      version: 2.23.1

    - groupId: com.mysql
      artifactId: mysql-connector-j
      version: 8.0.33

# Android no jar available
#    - groupId: androidx.core
#      artifactId: core-ktx
#      version: 1.13.1
#      repository:
#        id: google
#        url: https://maven.google.com/

    - groupId: org.jetbrains.kotlinx
      artifactId: kotlinx-coroutines-core
      version: 1.8.1

    - groupId: org.springframework
      artifactId: spring-beans
      version: 6.1.12

    - groupId: org.jetbrains
      artifactId: annotations
      version: 24.1.0

    - groupId: org.osgi
      artifactId: org.osgi.core
      version: 6.0.0

    - groupId: javax.inject
      artifactId: javax.inject
      version: 1

    - groupId: commons-collections
      artifactId: commons-collections
      version: 3.2.2

    - groupId: com.alibaba
      artifactId: fastjson
      version: 2.0.52

    - groupId: javax.annotation
      artifactId: javax.annotation-api
      version: 1.3.2

    - groupId: org.hamcrest
      artifactId: hamcrest-library
      version: 3.0

    - groupId: javax.validation
      artifactId: validation-api
      version: 2.0.1.Final

    - groupId: org.junit.jupiter
      artifactId: junit-jupiter-params
      version: 5.11.0

    - groupId: com.fasterxml.jackson.datatype
      artifactId: jackson-datatype-jsr310
      version: 2.17.2

    - groupId: org.clojure
      artifactId: tools.nrepl
      version: 0.2.13

    - groupId: javax.xml.bind
      artifactId: jaxb-api
      version: 2.3.1

    - groupId: org.jetbrains.kotlinx
      artifactId: kotlinx-coroutines-core-jvm
      version: 1.8.1

# Android- no jar available
#    - groupId: com.google.android.material
#      artifactId: material
#      version: 1.12.0
    #  repository:
    #    id: google
    #    url: https://maven.google.com/

    - groupId: ch.qos.logback
      artifactId: logback-core
      version: 1.5.7

    - groupId: org.json
      artifactId: json
      version: 20240303

    - groupId: clojure-complete
      artifactId: clojure-complete
      version: 0.2.5
      repository:
        id: clojars
        url: https://repo.clojars.org/


    - groupId: org.scala-js
      artifactId: scalajs-library_2.13
      version: 1.16.0

    - groupId: org.springframework
      artifactId: spring-webmvc
      version: 6.1.12

    - groupId: commons-beanutils
      artifactId: commons-beanutils
      version: 1.9.4

    - groupId: com.google.protobuf
      artifactId: protobuf-java
      version: 4.28.0

    - groupId: com.squareup.retrofit2
      artifactId: retrofit
      version: 2.11.0

    - groupId: org.apache.maven.plugin-tools
      artifactId: maven-plugin-annotations
      version: 3.15.0

    - groupId: org.jetbrains.kotlin
      artifactId: kotlin-android-extensions-runtime
      version: 2.0.20

    - groupId: org.hamcrest
      artifactId: hamcrest-core
      version: 3.0

    - groupId: com.google.inject
      artifactId: guice
      version: 7.0.0